# Generated by Django 3.0.7 on 2020-09-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='events/cover/')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(upload_to='events/event/'),
        ),
    ]
