# Generated by Django 3.0.7 on 2020-09-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Organized_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
