# Generated by Django 3.0.7 on 2020-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_event_organized_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
