# Generated by Django 3.0.7 on 2020-09-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_cover_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(choices=[('يناير', 'يناير'), ('فبراير', 'فبراير'), ('مارس', 'مارس'), ('ابريل', 'ابريل'), ('مايو', 'مايو'), ('يونيو', 'يونيو'), ('يوليو', 'يوليو'), ('اغسطس', 'اغسطس'), ('سبتمبر', 'سبتمبر'), ('أكتوبر', 'أكتوبر'), ('نوفيمبر', 'نوفيمبر'), ('ديسمبر', 'ديسمبر')], max_length=15),
        ),
    ]
