# Generated by Django 3.0.7 on 2020-06-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0004_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='cclass',
            new_name='Class',
        ),
    ]
