# Generated by Django 3.0.7 on 2020-06-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0005_auto_20200630_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
