# Generated by Django 3.0.7 on 2020-06-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0006_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='title_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='title_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
