# Generated by Django 3.0.7 on 2020-07-02 13:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0008_auto_20200701_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
