# Generated by Django 3.0.7 on 2020-07-02 13:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0009_auto_20200702_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='text',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='class',
            name='text',
        ),
        migrations.AddField(
            model_name='class',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
