# Generated by Django 3.0.7 on 2020-07-02 20:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0010_auto_20200702_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
