# Generated by Django 3.0.7 on 2020-07-03 15:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0011_auto_20200702_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='graph',
        ),
        migrations.AddField(
            model_name='category',
            name='body_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='body_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
