# Generated by Django 3.0.7 on 2020-07-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0013_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
