# Generated by Django 3.0.7 on 2020-07-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0014_auto_20200704_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='class',
            name='title_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
