# Generated by Django 3.0.7 on 2020-07-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0016_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photo',
            new_name='Cover',
        ),
    ]
