# Generated by Django 3.0.7 on 2020-07-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0017_auto_20200704_0754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
