# Generated by Django 3.0.7 on 2020-07-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0018_delete_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='categories/cover/')),
            ],
        ),
    ]
