# Generated by Django 3.0.7 on 2020-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0019_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='class',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
