# Generated by Django 3.0.7 on 2020-09-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0020_auto_20200903_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
