# Generated by Django 3.0.7 on 2020-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0022_auto_20200903_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brief',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
