# Generated by Django 3.0.7 on 2020-09-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0023_category_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brief',
            field=models.TextField(max_length=250),
        ),
    ]
