# Generated by Django 3.0.7 on 2020-09-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0024_auto_20200904_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
    ]
