# Generated by Django 3.0.7 on 2020-09-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0025_auto_20200905_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='brief',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
