# Generated by Django 3.0.7 on 2020-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200704_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='say',
            new_name='opinion',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='photo',
            field=models.ImageField(upload_to='home/opinion/'),
        ),
    ]
