# Generated by Django 3.0.7 on 2020-09-03 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200704_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
