# Generated by Django 3.0.7 on 2020-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_cover_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
