# Generated by Django 3.0.7 on 2020-09-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200914_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='title_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='welcome',
            name='title_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='welcome',
            name='title_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
