# Generated by Django 3.0.7 on 2020-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
