# Generated by Django 3.0.7 on 2020-09-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video_cover',
            field=models.ImageField(default=1, upload_to='About/video_cover/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.TextField(),
        ),
    ]
