# Generated by Django 3.0.7 on 2020-09-05 22:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200905_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
